import Head from 'next/head'
import Image from 'next/image'

import Link from '@/components/Link/Link'
import MenuLink from '@/components/Link/MenuLink'
import DownButton from '@/components/DownButton/DownButton'
import Projects from './projects'
import Resume from './resume'
import Skills from './skills'

import s from '../../public/self-pic.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rishabh Vemparala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='w-full min-h-screen flex flex-col snap-center'> 

        {/* Navbar */}
        <div className='h-14 bg-gradient-to-r from-aqua to-h-purple m-6 p-[2px] rounded-lg'>
          <div className='text-white font-light text-2xl h-full w-full bg-gray-900 rounded-lg flex flex-row pl-4 pr-4'>
            <div className='self-center m-2'>home</div>
            <div className='ml-auto self-center flex flex-row'>
              <div className='self-center m-2'>resume</div>
              <div className='self-center m-2'>contact</div>
            </div>

          </div>
        </div>

        {/* Hero Section */}
        <div className='flex sm:flex-row flex-col-reverse p-6 sm:mt-96 mt-auto m-lg:mb-6 sm:gap-0 gap-8'>
          <div className='flex flex-col font-bold text-white self-center'>
            <div className='md:text-8xl text-5xl text-transparent bg-clip-text bg-gradient-to-r from-aqua to-h-purple'>
              Rishabh Vemparala
            </div>
            <div className='font-light text-sm sm:text-lg '>
              Software Engineer and student at the University of Texas at Dallas
            </div>

            {/* links */}
            <div className='font-light text-md flex flex-row'>
              |<Link name={'github'} link={'https://github.com/rishixyz9'}/>|
              <Link name={'linkedIn'} link={'https://www.linkedin.com/in/rishabh-vemparala-8b6155205/'}/>|
              <Link name={'email'} link={'#'}/>|
            </div>
          </div>
          <Image alt="" src={s} className="rounded-full border-2 border-white ml-auto sm:mr-0 mr-auto sm:w-96 overflow-hidden object-center object-contain"/>
        </div>
      </div> 
      <Projects /> 
      <Projects />   
      {/* <Resume />
      <Skills /> */}
    </>
  )
}
