import Head from 'next/head'
import Link from '@/components/Link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rishabh Vemparala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='w-screen h-screen flex'> 

        {/* name */}
        <div className='flex flex-col font-bold text-white p-6 ml-48 mt-[50vh]'>
          <div className='text-5xl'>
            Rishabh Vemparala
          </div>
          <div className='font-light text-lg '>
            Software Engineer and student at the University of Texas at Dallas
          </div>
          {/* links */}
          <div className='font-light text-md flex flex-row'>
            |
            <Link name={'github'} link={'https://github.com/rishixyz9'}/>|
            <Link name={'linkedIn'} link={'https://www.linkedin.com/in/rishabh-vemparala-8b6155205/'}/>|
            <Link name={'email'} link={'#'}/>|
          </div>
        </div>

        <div className='flex flex-col font-bold text-white p-6 ml-48 mt-[50vh]'>
          <Link name={'projects'} link={'#'}/>
          <Link name={'resume'} link={'#'}/>
          <Link name={'about me'} link={'#'}/>
        </div>

      </div>
    </>
  )
}
