import Head from 'next/head'
import Link from '@/components/Link/Link'
import MenuLink from '@/components/Link/MenuLink'
import DownButton from '@/components/DownButton/DownButton'
import Projects from './projects'
import Resume from './resume'
import Skills from './skills'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rishabh Vemparala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <style>
      @import url('https://fonts.googleapis.com/css2?family=Montserrat&family=Outfit:wght@100;200;300;400;500;600;700;800&display=swap');
      </style>
      <div className='w-full h-screen flex flex-col snap-center'> 
        <div className='flex sm:flex-row flex-col mt-[50vh]'>
          {/* name */}
          <div className='flex flex-col font-bold text-white p-6 md:ml-48'>
            <div className='text-5xl'>
              Rishabh Vemparala
            </div>
            <div className='font-light text-lg '>
              Software Engineer and student at the University of Texas at Dallas
            </div>
            {/* links */}
            <div className='font-light text-md flex flex-row'>
              |
              <Link name={'github'} link={'https://github.com/rishixyz9'}/>|
              <Link name={'linkedIn'} link={'https://www.linkedin.com/in/rishabh-vemparala-8b6155205/'}/>|
              <Link name={'email'} link={'#'}/>|
            </div>
          </div>
          {/* menu */}
          <div className='sm:flex-col flex-row font-bold text-white sm:p-6 sm:ml-auto md:mr-60 self-center hidden sm:flex'>
            <MenuLink name={'projects'} link={'#projects'}/>
            <MenuLink name={'resume'} link={'#resume'}/>
            <MenuLink name={'about me'} link={'#'}/>
          </div>
        </div>

        <DownButton next={'projects'}/>
        
      </div>
      <Projects />
      <Resume />
      <Skills />
      
      
    </>
  )
}
